"""Tests for GitHub comment and HTML report output."""

from pathlib import Path
from unittest.mock import MagicMock

from pr_insight.analyzer.engine import ReviewFinding, ReviewReport
from pr_insight.github.models import FileChange, FileStatus, PRInfo
from pr_insight.output.github_comment import format_review_comment, post_review_comment
from pr_insight.output.html_report import generate_html_report


def _make_report() -> ReviewReport:
    pr = PRInfo(
        owner="o", repo="r", number=42, title="Fix critical bug", description="desc",
        author="dev", state="open", base_branch="main", head_branch="fix",
        url="https://github.com/o/r/pull/42", files_changed=2, additions=20, deletions=10,
        file_changes=[FileChange(
            "src/main.py",
            FileStatus.MODIFIED,
            20,
            10,
            "@@ -8,4 +8,4 @@ def query(sql):\n"
            " def query(sql):\n"
            "-    return db.execute(sql)\n"
            "+    return db.execute(sql, params={})\n",
        )],
    )
    report = ReviewReport(pr_info=pr)
    report.summary = {"purpose": "Fix bug", "impact": "core", "tech_details": "refactored"}
    report.risks = [
        ReviewFinding(file="src/main.py", line="10", severity="high", description="SQL injection", suggestion="Use params"),
        ReviewFinding(file="src/main.py", line="20", severity="medium", description="unused var", suggestion="remove"),
    ]
    report.suggestions = [
        ReviewFinding(file="src/main.py", line="15", severity="low", description="rename", suggestion="better name"),
    ]
    report.style_issues = [
        ReviewFinding(file="src/main.py", line="25", category="duplication", description="duplicate branch", suggestion="extract helper"),
    ]
    return report


class TestFormatReviewComment:
    def test_contains_header(self):
        md = format_review_comment(_make_report())
        assert "PR-Insight" in md

    def test_contains_stats(self):
        md = format_review_comment(_make_report())
        assert "| Risk | 2 (1 high / 1 medium) |" in md
        assert "| Review | 1 |" in md
        assert "| Style | 1 |" in md

    def test_contains_risks(self):
        md = format_review_comment(_make_report())
        assert "SQL injection" in md

    def test_contains_suggestions(self):
        md = format_review_comment(_make_report())
        assert "rename" in md

    def test_contains_style_issues(self):
        md = format_review_comment(_make_report())
        assert "duplicate branch" in md

    def test_contains_footer(self):
        md = format_review_comment(_make_report())
        assert "Generated by" in md

    def test_with_errors(self):
        report = _make_report()
        report.errors = ["timeout on chunk 1"]
        md = format_review_comment(report)
        assert "timeout" in md


class TestPostReviewComment:
    def test_calls_github_api(self):
        mock_gh = MagicMock()
        report = _make_report()
        post_review_comment(mock_gh, report)
        mock_gh.post_review_comment.assert_called_once()
        args = mock_gh.post_review_comment.call_args
        assert args[0][0] == "o"
        assert args[0][1] == "r"
        assert args[0][2] == 42


class TestGenerateHtmlReport:
    def test_creates_file(self, tmp_path):
        report = _make_report()
        out = tmp_path / "report.html"
        result = generate_html_report(report, out)
        assert result.exists()
        content = result.read_text()
        assert "Fix critical bug" in content
        assert "SQL injection" in content
        assert "<div class=\"label\">Risk</div>" in content
        assert "<div class=\"label\">Review</div>" in content
        assert "<div class=\"label\">Style</div>" in content
        assert "<th>View</th>" in content
        assert "data-file=\"src/main.py\"" in content
        assert "原始代码" in content
        assert "return db.execute(sql)" in content
        assert "return db.execute(sql, params={})" in content

    def test_creates_parent_dirs(self, tmp_path):
        report = _make_report()
        out = tmp_path / "sub" / "dir" / "report.html"
        generate_html_report(report, out)
        assert out.exists()

    def test_html_structure(self, tmp_path):
        report = _make_report()
        out = tmp_path / "report.html"
        content = generate_html_report(report, out).read_text()
        assert "<!DOCTYPE html>" in content
        assert "<table>" in content
        assert "PR-Insight" in content
