"""Post review results as GitHub PR comments."""

from __future__ import annotations

from ..analyzer.engine import ReviewReport
from ..github.client import GitHubClient


def format_review_comment(report: ReviewReport) -> str:
    """Format the review report as a Markdown comment for GitHub."""
    stats = report.stats
    pr = report.pr_info

    lines = [
        "## PR-Insight AI Review",
        "",
        f"**PR:** #{pr.number} {pr.title}",
        f"**Changes:** {pr.files_changed} files, +{pr.additions}/-{pr.deletions}",
        "",
        "### Summary",
        "",
    ]

    summary = report.summary
    if summary.get("purpose"):
        lines.append(f"**Purpose:** {summary['purpose']}")
    if summary.get("impact"):
        lines.append(f"**Impact:** {summary['impact']}")
    if summary.get("tech_details"):
        lines.append(f"**Details:** {summary['tech_details']}")
    lines.append("")

    # Stats
    lines.append("### Statistics")
    lines.append("")
    lines.append(f"| Category | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Risk | {stats['risks']} ({stats['high_risk']} high / {stats['medium_risk']} medium) |")
    lines.append(f"| Review | {stats['suggestions']} |")
    lines.append(f"| Style | {stats['style_issues']} |")
    lines.append("")

    # Top risks (limit to 10)
    if report.risks:
        lines.append("### Risk")
        lines.append("")
        for r in report.risks[:10]:
            icon = {"high": "!!", "medium": "!", "low": "i"}.get(r.severity, "?")
            location = f"`{r.file}:{r.line}`" if r.file else ""
            lines.append(f"- **[{icon} {r.severity.upper()}]** {r.description} {location}")
            if r.suggestion:
                lines.append(f"  - Suggestion: {r.suggestion}")
        lines.append("")

    # Top suggestions (limit to 5)
    if report.suggestions:
        lines.append("### Review")
        lines.append("")
        for s in report.suggestions[:5]:
            location = f"`{s.file}:{s.line}`" if s.file else ""
            lines.append(f"- {s.description} {location}")
            if s.suggestion:
                lines.append(f"  - {s.suggestion}")
        lines.append("")

    if report.style_issues:
        lines.append("### Style")
        lines.append("")
        for s in report.style_issues[:5]:
            location = f"`{s.file}:{s.line}`" if s.file else ""
            lines.append(f"- {s.description} {location}")
            if s.suggestion:
                lines.append(f"  - {s.suggestion}")
        lines.append("")

    if report.errors:
        lines.append("### Analysis Errors")
        lines.append("")
        for e in report.errors:
            lines.append(f"- {e}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [PR-Insight](https://github.com/christianlsl/PR-Insight)*")

    return "\n".join(lines)


def post_review_comment(
    gh_client: GitHubClient,
    report: ReviewReport,
) -> None:
    """Format and post the review as a GitHub PR comment."""
    body = format_review_comment(report)
    pr = report.pr_info
    gh_client.post_review_comment(pr.owner, pr.repo, pr.number, body)
